<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FurnitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FurnitureRepository extends EntityRepository
{
    public function _findAll()
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('a')
            ->from($this->_entityName, 'a')
        ;
        return $queryBuilder->getQuery()->getResult();
    }

    public function _findOne($id)
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('a')
            ->from($this->_entityName, 'a')
            ->where('a.id = '.$id)
        ;
        return $queryBuilder->getQuery()->getResult();
    }
}
