<?php

namespace AppBundle\Repository;

/**
 * FurnitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FurnitureRepository extends \Doctrine\ORM\EntityRepository
{
}
