app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#fos_furniture:
#    resource: "@FOSFurnitureBundle/Resources/config/routing/all.xml"

rest :
    type : rest
    resource : "@AppBundle/Ressources/config/routing_api.yml"
    prefix : /api

api_login_check:
    path: /api/login_check

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /api/doc