app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#fos_furniture:
#    resource: "@FOSFurnitureBundle/Resources/config/routing/all.xml"

rest :
    type : rest
    resource : "@AppBundle/Ressources/config/routing_api.yml"
    prefix : /api
